name: Deploy Node.js Backend to EC2

on:
  push:
    branches:
      - main   

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}        
          username: ${{ secrets.EC2_USER }}    
          key: ${{ secrets.EC2_KEY }}          
          script: |
            cd /home/ubuntu/Demo_Back
            git fetch --all
            git reset --hard origin/main
            npm install
            pm2 restart Demobackend || pm2 start index.js --name Demobackend
            pm2 save
            sudo systemctl restart nginx
